title: "Yakir Hadad — CV/DL"
description: "Computer Vision & Deep Learning — real-time vision systems, multispectral registration."
theme: jekyll-theme-minimal
logo: /assets/avatar.svg
show_downloads: false

author: Yakir Hadad
email: yakirhadad18@gmail.com
url: https://yakirEng.github.io

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

github:
  is_project_page: false
